support acl as hujson
kazauwa/ansible-role-headscale pull request #10
Opened 2024-11-17 15:14 UTC by nitbx

Quick fix for my needs

Notes:
- Need to validate additional breaking changes with the version update to 0.23.0.

- Removed `headscale_acl` as YAML:
   - Jinja templates are no longer used for this.

2024-11-21 20:49 UTC, kazauwa requested changes
Hey, thank you for submitting these changes! I left two small comments, please have a look at them. Also, could you please drop a line or two in [CHANGELOG.MD](https://github.com/kazauwa/ansible-role-headscale/blob/main/CHANGELOG.MD) describing the changes you made? Take a look at [keep a changelog](https://keepachangelog.com/en/1.0.0/) and [this commit](https://github.com/kazauwa/ansible-role-headscale/commit/66aeb3d0d3b03828c4299e6d490ad329f54d2071) as a reference.

Thanks!

2024-11-21 20:49 UTC, kazauwa commented on tasks/configure.yml
> +    dest: '{{ headscale_config_dir }}/acl.json'
Let's call it `acl.hujson` to avoid confusion since technically it's not a normal JSON.

2024-11-21 20:49 UTC, kazauwa commented on README.md
> +  - Description: path to HuJSON formatted headscale acl file.
I think a link to ACL syntax here would be helpful for a reader: https://tailscale.com/kb/1337/acl-syntax

2024-11-23 17:11 UTC, nitbx commented
first time doing a changelog. Feel free to propose changes :open_hands:

2024-11-25 08:23 UTC, kazauwa requested changes
Two small nits and two linter warnings (sorry about that, didn't realize it wasn't running) and let's merge it!

2024-11-25 08:23 UTC, kazauwa commented on CHANGELOG.MD
> +### Fixed
I think we can omit "Fixed" section as this is a new feature, rather than a fix of an old bug.

2024-11-25 08:23 UTC, kazauwa commented on CHANGELOG.MD
> +- Removed the capability of having ACL yaml formated to be outputted in the in a file. ([0c79226](https://github.com/kazauwa/ansible-role-headscale/blob/1cbe9432ae53c3042a45506fd48f3dd203e24c97/tasks
typo - `...in the in a...`

2025-01-08 14:40 UTC, nitbx reviewed
i forgot to do that?

2025-01-30 15:25 UTC, fr6nco commented
any updates on this? Hitting this too right now. @kazauwa

2025-02-24 23:47 UTC, kazauwa commented
Hey all, apologies for the delay. Life happened and I completely forgot about this. I'll have a look tomorrow and likely merge and release the new version afterwards.

2025-02-25 21:44 UTC, kazauwa approved these changes
LGTM

2025-02-25 21:50 UTC, merged